property_types = [
    "commonsMedia",
    "external-id",
    "geo-shape",
    "globe-coordinate",
    "math",
    "monolingualtext",
    "quantity",
    "string",
    "tabular-data",
    "time",
    "url",
    "wikibase-form",
    "wikibase-item",
    "wikibase-lexeme",
    "wikibase-property",
    "wikibase-sense",
]
