property_types = {
    "CommonsMedia": "commonsMedia",
    "ExternalId": "external-id",
    "Form": "wikibase-form",
    "GeoLocation": "globe-coordinate",
    "GeoShape": "geo-shape",
    "Item": "wikibase-item",
    "Lexeme": "wikibase-lexeme",
    "Math": "math",
    "Property": "wikibase-property",
    "Quantity": "quantity",
    "Sense": "wikibase-sense",
    "str": "string",
    "Table": "tabular-data",
    "Time": "time",
    "Url": "url",
}
